"""Download the web fonts into fonts/ and emit fonts/fonts.css.

Self-hosting removes two third-party connections from the critical path and
keeps visitor requests off Google's servers. Only the latin subsets are kept;
the site has no Greek, Cyrillic or Vietnamese copy.
"""
import re, sys, urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FONT_DIR = ROOT / "fonts"
KEEP = {"latin", "latin-ext"}
UA = ("Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 "
      "(KHTML, like Gecko) Chrome/120.0.0.0 Safari/537.36")
SOURCES = [
    ("Manrope", "https://fonts.googleapis.com/css2?family=Manrope:wght@400..700&display=swap"),
    ("DM Mono", "https://fonts.googleapis.com/css2?family=DM+Mono:wght@400;500&display=swap"),
]
BLOCK = re.compile(r"/\*\s*([\w-]+)\s*\*/\s*(@font-face\s*\{.*?\})", re.S)

def get(url: str) -> bytes:
    return urllib.request.urlopen(urllib.request.Request(url, headers={"User-Agent": UA}), timeout=30).read()

def main() -> None:
    FONT_DIR.mkdir(parents=True, exist_ok=True)
    faces, downloaded = [], 0
    for family, url in SOURCES:
        css = get(url).decode()
        for subset, block in BLOCK.findall(css):
            if subset not in KEEP:
                continue
            src = re.search(r"url\((https://[^)]+\.woff2)\)", block)
            weight = re.search(r"font-weight:\s*([\d ]+);", block).group(1).strip()
            if not src:
                continue
            name = f"{family.lower().replace(' ', '-')}-{weight.replace(' ', '-')}-{subset}.woff2"
            target = FONT_DIR / name
            if not target.exists():
                target.write_bytes(get(src.group(1)))
                downloaded += 1
            # Reference the file relative to fonts.css so the site works from any base path.
            faces.append(f"/* {family} {weight} - {subset} */\n"
                         + block.replace(src.group(1), name).rstrip())
    if not faces:
        sys.exit("No font faces matched; the Google Fonts response format may have changed.")
    header = ("/* Generated by tools/fetch_fonts.py - do not edit by hand.\n"
              "   Manrope and DM Mono are licensed under the SIL Open Font License 1.1;\n"
              "   see fonts/OFL.txt. */\n\n")
    (FONT_DIR / "fonts.css").write_text(header + "\n\n".join(faces) + "\n", encoding="utf-8")
    total = sum(f.stat().st_size for f in FONT_DIR.glob("*.woff2"))
    print(f"{len(faces)} faces, {downloaded} newly downloaded, {total:,} bytes of woff2")

if __name__ == "__main__":
    main()
